/**
 * Test Harness Module — game loading, scenario management, and state manipulation.
 *
 * Provides the core logic for the test harness page:
 * - Dynamic game discovery (via virtual:game-list Vite module — enumerates libs/games/ dirs)
 * - Game session creation via server API
 * - Scenario file loading (apply a saved JSON state to a session)
 * - Scenario export (save current state as a reusable JSON file)
 * - State manipulation via dev endpoints (trigger round end, game end, set-state)
 */

import { browser } from '$app/environment';

// Browser: /api prefix proxied by Vite to server:8080 (works from host and Docker)
// SSR: use Docker service name directly
const API_BASE = browser ? '/api' : 'http://server:8080';

export function getApiBase(): string {
  return API_BASE;
}

/**
 * Dynamically discovers available game IDs from the virtual:game-list Vite module.
 * This module is generated by the gameWatcherPlugin in vite.config.ts, enumerating
 * all directories under libs/games/ that contain a game.json file.
 * Falls back to an empty list if the virtual module is not available (SSR).
 */
export async function discoverGames(): Promise<string[]> {
  try {
    const mod = await import('virtual:game-list');
    return mod.default as string[];
  } catch {
    return [];
  }
}

/**
 * Fetches and returns the raw game.json content for a given game ID.
 * Uses the dev server endpoint for reliability across Docker environments.
 */
export async function fetchGameConfig(gameId: string): Promise<unknown> {
  const res = await fetch(`${API_BASE}/dev/game-config/${gameId}`);
  if (res.ok) return res.json();
  throw new Error(`Game config not found for: ${gameId}`);
}

/**
 * Creates a new game session for testing.
 * Uses bot player names for simplicity.
 */
export async function createTestGame(gameId: string, playerCount: number = 2): Promise<{ sessionId: string }> {
  const playerNames = Array.from({ length: playerCount }, (_, i) => `Bot-${i + 1}`);
  const res = await fetch(`${API_BASE}/games`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ gameId, playerNames })
  });
  if (!res.ok) throw new Error(`Failed to create game: ${res.status}`);
  const data = await res.json();
  return { sessionId: data.sessionId };
}

/**
 * Fetches the current game state and valid moves.
 */
export async function fetchGameState(sessionId: string) {
  const res = await fetch(`${API_BASE}/dev/${sessionId}/state`);
  if (!res.ok) throw new Error(`Failed to fetch state: ${res.status}`);
  return res.json();
}

/**
 * Loads a scenario JSON file and applies it to the current session via /dev/set-state.
 */
export async function loadScenario(sessionId: string, scenarioJson: string): Promise<void> {
  const scenario = JSON.parse(scenarioJson);
  const res = await fetch(`${API_BASE}/dev/${sessionId}/set-state`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(scenario)
  });
  if (!res.ok) throw new Error(`Failed to apply scenario: ${res.status}`);
}

/**
 * Exports the current game state as a scenario JSON string.
 */
export async function exportScenario(sessionId: string): Promise<string> {
  const { state } = await fetchGameState(sessionId);
  const stateObj = typeof state === 'string' ? JSON.parse(state) : state;
  return JSON.stringify(stateObj, null, 2);
}

/**
 * Triggers round end via dev endpoint.
 */
export async function triggerRoundEnd(sessionId: string) {
  const res = await fetch(`${API_BASE}/dev/${sessionId}/trigger-round-end`, { method: 'POST' });
  if (!res.ok) throw new Error(`Failed to trigger round end: ${res.status}`);
  return res.json();
}

/**
 * Triggers game end via dev endpoint.
 */
export async function triggerGameEnd(sessionId: string) {
  const res = await fetch(`${API_BASE}/dev/${sessionId}/trigger-game-end`, { method: 'POST' });
  if (!res.ok) throw new Error(`Failed to trigger game end: ${res.status}`);
  return res.json();
}

/**
 * Sets arbitrary state properties via dev endpoint.
 */
export async function setState(sessionId: string, overrides: Record<string, unknown>) {
  const res = await fetch(`${API_BASE}/dev/${sessionId}/set-state`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(overrides)
  });
  if (!res.ok) throw new Error(`Failed to set state: ${res.status}`);
  return res.json();
}
